### ISSUE TITLE
A bit of code review

### ISSUE THREAD

**Issue by pacak** [Anmsh27/rs-logger#1]
https://github.com/Anmsh27/rs-logger/blob/33502efd8c0aa0da21d311bc632fb31554d2df70/src/lib.rs#L49C24-L54C10

```
let json = filename.ends_with(".json");
```

But you shouldn't use `String` for file names.

---

https://github.com/Anmsh27/rs-logger/blob/33502efd8c0aa0da21d311bc632fb31554d2df70/src/lib.rs#L99C1-L100C29

Drop the whole line? I think `cargo clippy` might make some suggestions.

---

```rust
        let msg_parsed = msg.replace("%D", &date_string).replace("%T", &time);
```

I'm not sure if I encountered any scenarios where I wanted to insert error date/time to the error message, but I had several cases where I had to log an URL. `%D` can be a part of percent encoded string: https://en.wikipedia.org/wiki/Percent-encoding

---

```
                self.file
                    .write(&mut file_formatted.as_bytes())
                    .unwrap_or_else(|_| {
                        println!("Error in writing to file. msg: {}", msg_parsed);
                        0 as usize
                    });
```
https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all

---

```
    pub fn warning(&mut self, msg: String) {
    pub fn info(&mut self, msg: String) {
    pub fn debug(&mut self, msg: String) {
```

The differences are: color, message prefix and a pattern. Everything else is just copy-pasted. Deduplicate?

---

https://github.com/Anmsh27/rs-logger/blob/33502efd8c0aa0da21d311bc632fb31554d2df70/src/lib.rs#L366

The way it currently used - it will always allocate two strings and perform a call to chrono even if logging to the file is off and there's no date formatting tokens. Expensive...

---

Still doesn't pass the sniff test, but it's getting better! :tada:

**Comment by Anmsh27** [comment]
I think i get most of the criticisms, but could you elaborate on the fourth one?

**Comment by pacak** [comment]
> criticisms

Opportunities to improve.

> but could you elaborate on the fourth one?

Sure. `write` is done with a syscall which can get interrupted with a signal. In this case it will return `ErrorKind::Interrupted` the right thing to do when you get this kind of error is to retry the opperations, `write_all` does exactly that.

A few links:

- https://unix.stackexchange.com/questions/253349/what-is-the-rationale-behind-eintr
- https://softwareengineering.stackexchange.com/questions/267748/proper-way-of-handling-eintr-in-libraries

**Comment by Anmsh27** [comment]
> But you shouldn't use String for file names.

Should i take in a &str and then own it? I think storing filenames as &str would require the use of lifetimes

> I'm not sure if I encountered any scenarios where I wanted to insert error date/time to the error message, but I had several cases where I had to log an URL. %D can be a part of percent encoded string:

I dont get this either. Do you mean that %D is a reserved character like how %3D means "="? So when urls are entered, it would replace the characters with the date even tho that wasnt the intention. I think i should change it to some other pattern then since % is already used

> The differences are: color, message prefix and a pattern. Everything else is just copy-pasted. Deduplicate?

Yeah im trying to fix this atm. 

Thanks!

**Comment by pacak** [comment]
> Should i take in a &str and then own it?

No, you want to use `PathBuf` to represent file names. Documentation for `OsString` contains a bit more explanations.     

> I dont get this either. Do you mean that %D is a reserved character like how %3D means "="?

https://en.wikipedia.org/wiki/Percent-encoding?useskin=vector#Binary_data

`%D` is not a reserved character, but `%D1` can be part of a binary blob

**Comment by Anmsh27** [comment]
I think i fixed all of the shortcomings. Thoughts?

**Comment by pacak** [comment]
Do you use `file` in `LoggerBuilder`?
```rust
pub struct LoggerBuilder {
    file: Option<fs::File>, // <---
```
---

I don't think you need to convert `OsString` to  `str` in order to compare it with `str`.
```rust
                    if i.to_str().unwrap() == "json" {
                        self.json = Some(true)
                    } else {
                        self.json = Some(false)
                    }
```

```rust
self.json = Some(i == "json")
```

---
```
    pub fn get_filename(&self) -> Option<&PathBuf> {
        self.filename.as_ref()
    }
```

Reference `PathBuf` is `&Path`, same as `String` and `&str`.

---
this

```rust
        let formatted;
        match level {
            Trace => {
                formatted = format!("DEBUG: {}", msg_parsed);
            }
            Info => {
                formatted = format!("INFO: {}", msg_parsed);
            }
            Warning => {
                formatted = format!("WARNING: {}", msg_parsed);
            }
            Error => {
                formatted = format!("ERROR: {}", msg_parsed);
            }
            Critical => {
                formatted = format!("CRITICAL: {}", msg_parsed);
            }
        };
```
is really this
```rust
        let formatted = match level {
            Trace => format!("DEBUG: {}", msg_parsed),
            Info => format!("INFO: {}", msg_parsed),
            Warning => format!("WARNING: {}", msg_parsed),
            Error => format!("ERROR: {}", msg_parsed),
            Critical => format!("CRITICAL: {}", msg_parsed),
        };
```
and is really this, if you have `impl Display for LoggingLevel` - it is used in a few places

```rust
let formatted = format!("{}: {}", level, msg_parsed);
```
same in `get_file_formatted`
---

```rust
                let file = fs::File::create(filename)?;
                file
```
this is just this: `fs::File::create(filename)?`. Did you try running clippy?

---

```rust
    ///
    /// Only works until and for LoggingLevel::Warning
    pub fn warning(&mut self, msg: String) {
        use LoggingLevel::*;

        let (date_string, time) = self.get_date_time_checked(&msg);

        let (formatted, msg_parsed) = self.parse_args(&msg, &date_string, &time, Warning);

        match self.level {
            Trace | Info | Warning => println!("{}", &formatted.bright_yellow()),
            _ => {}
        }

        if self.log_to_file {
            let file_formatted = self.get_file_formatted(&msg_parsed, &date_string, &time, Warning);
            self.write_to_file(&date_string, &time, &msg_parsed, &file_formatted, Warning)
        }
    }
```

This would always allocate, multiple times. I'd make it something like this and have whole logic shared in log_level

```rust
fn warning(&mut self, msg: impl AsRef<str>) {
    if self.level < LogLevel::Warning {
        self.log_level(msg, LogLevel::Warning);
    }
}
```

**Comment by pacak** [comment]
And yea, the rest is more or less fixed.

**Comment by Anmsh27** [comment]
> Do you use file in LoggerBuilder?

Fixed.

> I don't think you need to convert OsString to str in order to compare it with str.

Also fixed. I didnt know they were comaprable like that.

> Reference PathBuf is &Path, same as String and &str.

The compiler still throws an error saing it expects an &PathBuf.

> and is really this, if you have impl Display for LoggingLevel - it is used in a few places

Done

> This would always allocate, multiple times. I'd make it something like this and have whole logic shared in log_level

Also fixed.

**Comment by pacak** [comment]
> The compiler still throws an error saing it expects an &PathBuf.

Hmm... Can you show the code?

**Comment by Anmsh27** [comment]
![Screenshot 2024-03-11 075558](https://github.com/Anmsh27/rs-logger/assets/91868364/9e9c2806-cd8e-4482-8912-8f184f9a2b94)

**Comment by pacak** [comment]
you want `.as_deref()`

**Comment by Anmsh27** [comment]
Ahh ok
